# Site settings
title: 容我三思
email: zhuyue.sut@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  here is the description space.
baseurl: # the subpath of your site, e.g. /blog/
url: "http://blog.jinny.love" # the base hostname & protocol for your site
twitter_username: 
github_username:  zhuyuesut

# Build settings
markdown: kramdown
